# promptfooconfig.yaml
# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Pruebas para 30 prompts - JavaScript junior (Prompts externos y tests externos)'

env: 
  GEMINI_API_KEY: AIzaSyC1x9QRvWyl6cKmWO1yKpSGBSTEdmWBph4

prompts:
  - file://prompts/*.txt

providers:
  - "google:gemini-2.5-pro"

defaultTest: file://tests/tests.yml

